version: '3'
services:
  claims:
    #build: /home/azureuser/claims
    image: claims
    container_name: claims
    ports:
    - "9000:9000"
    #links:
    #- eureka-server
    #environment:
    #  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://20.163.181.235:8761/eureka
   mongodb:
    image : mongo
    container_name: claimsdb
    ports:
     - "2717:27017"
    restart: unless-stopped
 
