version: '4'
services:
  claims:
    build: .
    image: claims
    container_name: claims
    restart: always
    ports:
    - "9000:9000"
    links:
    - mongodb
    networks:
      - claims_default
    #environment:
    #  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://20.163.181.235:8761/eureka
   mongodb:
    image : mongo
    container_name: claimsdb
    ports:
     - "2717:27017"
    restart: unless-stopped
    networks:
      - claims_default
   networks:
     claims_default
     name: claims_default
    
 
